#!/usr/bin/env bash

set -x

dir="$(realpath $(dirname $(realpath $0)))"

sudo -v

(ssh-add -l | grep -F "$(ssh-keygen -lf ~/.ssh/id_ed25519)" -q) || ssh-add ~/.ssh/id_ed25519

# Assume that the Emacs source directory is this directory's sibling
cd "$dir/../emacs"

read -en1 -p "\"y\" to update \"$(git symbolic-ref --short HEAD)\": " yes

# git remote add emacs-lsp https://github.com/emacs-lsp/emacs 2>/dev/null

if [[ $yes == "y" ]]; then
    # "$dir/bin-merge-push-repo" emacs-29 # emacs-lsp json-rpc
    "$dir/bin-merge-push-repo" emacs-30 # emacs-lsp json-rpc
fi

cd "$dir"

./bin-install
