#!/usr/bin/env bash

dir="$(realpath $(dirname $0))"

sudo -v

./bin-ensure-updated-source-to-build

time makepkg -si --noconfirm

./bin-post-install

./bin-tag-pkg-tar-after-build *$(uname -m).pkg.tar.zst
