#!/usr/bin/env bash

# Must be ran inside the source repository directory

# set -euo pipefail
# IFS=$'\n\t'

# Auto-abort merge conflicts, not possible when bash exits after those arise
function abort_merge_conflicts() {
    if [[ ! $(git ls-files -u) = "" ]]; then
        echo "💗  Aborting merge"
        git merge --abort
    fi
}

function fetch_merge() {
    remote="$1"
    branch="$2"
    echo "💗  Updating $branch"
    git fetch --update-head-ok $remote $branch:$branch

    echo "💗  Merging from $remote/$branch"
    git merge --no-edit $remote/$branch
    abort_merge_conflicts
}

set -x

git remote get-url upstream &>/dev/null ||
    git remote add upstream https://github.com/emacs-mirror/emacs

# git fetch --all

upstream_branch="${1}"

fetch_merge upstream $upstream_branch

[[ -n "$3" ]] && fetch_merge $2 $3

# In case a commit message breaks
git push --all || git push --all --no-verify
