#!/usr/bin/env bash

set -x

emacs_dir=~/.config/emacs

if [[ -n "$1" ]]; then

    build_dir=~/.cache/tree-sitter-module

    if [[ -d $build_dir ]]; then
        cd $build_dir
        git pull
    else
        git clone https://github.com/casouri/tree-sitter-module "$build_dir"
    fi

else
    build_dir="$(dirname $0)/src/emacs/admin/notes/tree-sitter/build-module/"
fi

module_dir=$emacs_dir/tree-sitter

mkdir -p $emacs_dir

cd $build_dir

./batch.sh

mkdir -p $module_dir
mv $build_dir/dist/* $module_dir

[[ -n "$1" ]] || rm -rf $build_dir/dist

doom_treesit_module_dir=~/.config/emacs/.local/cache/tree-sitter
mkdir -p "$(dirname $doom_treesit_module_dir)"
test -d $doom_treesit_module_dir || ln -s -T $module_dir $doom_treesit_module_dir
